using LookBackHistory.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using static System.Console;

namespace LookBackHistory.Views
{
	/// <summary>
	/// SearchTabItem.xaml の相互作用ロジック
	/// </summary>
	public partial class SearchTabItem : UserControl
	{
		public SearchTabItem()
		{
			InitializeComponent();
		}

		private void DataGrid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
		{
			var star = new DataGridLength(1.0d, DataGridLengthUnitType.Auto);

			switch (e.PropertyName)
			{
				case "Title":
					e.Column.Width = star;
					break;
				case "Url":
					e.Column.Width = star;
					break;
				case "LastAccess":
					e.Column.Width = star;
					break;
				default:
					e.Column.Visibility = Visibility.Collapsed;
					break;
			}
		}

		private void DataGrid_AutoGeneratedColumns(object sender, EventArgs e)
		{
			
        }

		private void UserControl_MouseDoubleClick(object sender, MouseButtonEventArgs e)
		{
			var item = (HistoryObject)dataList.SelectedItem;
			if (item == null) return;
			var element = (UIElement)dataList.ItemContainerGenerator.ContainerFromItem(item);
			if (element.InputHitTest(e.GetPosition(element)) == null) return;

			WriteLine(item.Url);
			System.Diagnostics.Process.Start(item.Url);
		}
	}
}
